### ISSUE TITLE
Add default tf2 dir for 32bit

### ISSUE THREAD

**Issue by Margen67** [GoodOldJack12/Team-Comtress-2-Installer#1]
* Add default `--tf2dir` (i.e. `%PROGRAMFILES(X86)%\Steam\steamapps\common\Team Fortress 2` for 64 bit, and `%PROGRAMFILES%\Steam\steamapps\common\Team Fortress 2` for 32 bit)
* ~~Add option to install stock build as described in [this guide](https://github.com/mastercomfig/team-comtress-2/wiki/Advanced-Installation-Instructions).~~

**Comment by GoodOldJack12** [comment]
> * Add default `--tf2dir` (i.e. `%PROGRAMFILES(X86)%\Steam\steamapps\common\Team Fortress 2` for 64 bit, and `%PROGRAMFILES%\Steam\steamapps\common\Team Fortress 2` for 32 bit)

This is a good idea and can be fairly easily implemented in the auto-config. I do want to point out that that value is already the 64bit path by default.

> * Add option to install stock build as described in [this guide](https://github.com/mastercomfig/team-comtress-2/wiki/Advanced-Installation-Instructions).

I've been thinking about this (although I was thinking about using steamcmd instead of the suggested tools). The only problem with this is that it depends on other programs, which either makes the installer heavier or requires the program to be already installed. In addition to that, these methods require authentication. 

If I or someone else figures out a way to do this in an elegant way, we can revisit that feature.

I will accept your first suggestion and edit this issue accordingly.

**Comment by GoodOldJack12** [comment]
The implementation of this feature is a little different from the original description.
The autoconfig will try and detect if TF2 is installed in the 64bit or the 32bit path (or installed at all).

This will prevent edge cases where somehow tf2 ended up in the 32bit folder on a 64bit OS.
